apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    instance: status.lib.unb.ca
    tier: status
    uri: status.lib.unb.ca
  name: status-lib-unb-ca
  namespace: prod
spec:
  selector:
    matchLabels:
      uri: status.lib.unb.ca
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx
        instance: status.lib.unb.ca
        tier: status
        uri: status.lib.unb.ca
    spec:
      nodeSelector:
        deployenv: prod
      containers:
        -
          env:
            -
              name: DEPLOY_ENV
              value: prod
          image: "||DEPLOYMENTIMAGE||"
          imagePullPolicy: Always
          name: status-lib-unb-ca
          ports:
            -
              containerPort: 80
          volumeMounts:
            -
              mountPath: /app/html/data
              name: status-persistent-storage
      priorityClassName: high-priority-services
      imagePullSecrets:
        -
          name: github-container-registry-auth
      restartPolicy: Always
      volumes:
        -
          name: status-persistent-storage
          persistentVolumeClaim:
            claimName: status-lib-unb-ca
